import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  Trophy,
  Award,
  Zap,
  Sparkles,
  Flame,
  Calendar,
  Swords,
  Share2,
  Copy,
  Check,
  CheckCircle2,
  ArrowLeft,
  Loader2,
  User,
  Users,
  Gamepad2,
  ShoppingBag,
  Play,
  Clock,
  AlertCircle,
  X,
  Globe,
  Timer,
  Flag,
  Lock,
  RotateCcw,
  ExternalLink,
  Coins,
  Pins,
  Sliders,
  Gift,
  Crown,
  History,
  Pin,
  Rocket,
  ShieldCheck,
  Plus,
  Palette,
  SquareAsterisk,
  Image,
  Tag,
  MousePointerClick,
  Shield,
  Medal,
  Gem,
  WifiOff,
} from './icons.js';

describe('Hugeicons Stroke-Rounded Icons', () => {
  it('exports all application icons as defined components', () => {
    const icons = [
      Trophy,
      Award,
      Zap,
      Sparkles,
      Flame,
      Calendar,
      Swords,
      Share2,
      Copy,
      Check,
      CheckCircle2,
      ArrowLeft,
      Loader2,
      User,
      Users,
      Gamepad2,
      ShoppingBag,
      Play,
      Clock,
      AlertCircle,
      X,
      Globe,
      Timer,
      Flag,
      Lock,
      RotateCcw,
      ExternalLink,
      Coins,
      Pins,
      Sliders,
      Gift,
      Crown,
      History,
      Pin,
      Rocket,
      ShieldCheck,
      Plus,
      Palette,
      SquareAsterisk,
      Image,
      Tag,
      MousePointerClick,
      Shield,
      Medal,
      Gem,
      WifiOff,
    ];

    for (const icon of icons) {
      assert.ok(icon, 'Icon component should be defined');
      assert.equal(typeof icon, 'object', 'forwardRef returns an object component');
    }
  });

  it('aliases Pins to Coins for game coin display', () => {
    assert.equal(Pins, Coins);
  });
});
