export type FlagTier = 1 | 2 | 3 | 4;

export type Continent = 'africa' | 'asia' | 'europe' | 'americas' | 'oceania' | 'world';

export interface CountryFlag {
  isoCode: string;
  name: string;
  tier: FlagTier;
  continent: Continent;
}

export const CONTINENT_LABELS: Record<Continent, string> = {
  world: 'All World',
  africa: 'Africa',
  asia: 'Asia',
  europe: 'Europe',
  americas: 'Americas',
  oceania: 'Oceania',
};

export type RunTierMix = Record<FlagTier, number>;

export const DEFAULT_RUN_TIER_MIX: RunTierMix = {
  1: 4,
  2: 3,
  3: 2,
  4: 1,
};

export const COUNTRIES: CountryFlag[] = [
  { isoCode: 'us', name: 'United States', tier: 1, continent: 'americas' },
  { isoCode: 'gb', name: 'United Kingdom', tier: 1, continent: 'europe' },
  { isoCode: 'ca', name: 'Canada', tier: 1, continent: 'americas' },
  { isoCode: 'fr', name: 'France', tier: 1, continent: 'europe' },
  { isoCode: 'de', name: 'Germany', tier: 1, continent: 'europe' },
  { isoCode: 'it', name: 'Italy', tier: 1, continent: 'europe' },
  { isoCode: 'jp', name: 'Japan', tier: 1, continent: 'asia' },
  { isoCode: 'br', name: 'Brazil', tier: 1, continent: 'americas' },
  { isoCode: 'es', name: 'Spain', tier: 1, continent: 'europe' },
  { isoCode: 'cn', name: 'China', tier: 1, continent: 'asia' },
  { isoCode: 'kr', name: 'South Korea', tier: 1, continent: 'asia' },
  { isoCode: 'in', name: 'India', tier: 1, continent: 'asia' },
  { isoCode: 'tr', name: 'Turkey', tier: 1, continent: 'europe' },
  { isoCode: 'ru', name: 'Russia', tier: 1, continent: 'europe' },
  { isoCode: 'gr', name: 'Greece', tier: 1, continent: 'europe' },
  { isoCode: 'mx', name: 'Mexico', tier: 1, continent: 'americas' },
  { isoCode: 'ar', name: 'Argentina', tier: 1, continent: 'americas' },
  { isoCode: 'za', name: 'South Africa', tier: 1, continent: 'africa' },
  { isoCode: 'se', name: 'Sweden', tier: 1, continent: 'europe' },
  { isoCode: 'ch', name: 'Switzerland', tier: 1, continent: 'europe' },
  { isoCode: 'pt', name: 'Portugal', tier: 1, continent: 'europe' },
  { isoCode: 'eg', name: 'Egypt', tier: 1, continent: 'africa' },
  { isoCode: 'sa', name: 'Saudi Arabia', tier: 1, continent: 'asia' },
  { isoCode: 'ps', name: 'Palestine', tier: 1, continent: 'asia' },
  { isoCode: 'cu', name: 'Cuba', tier: 1, continent: 'americas' },
  { isoCode: 'jm', name: 'Jamaica', tier: 1, continent: 'americas' },
  { isoCode: 'no', name: 'Norway', tier: 1, continent: 'europe' },

  { isoCode: 'be', name: 'Belgium', tier: 2, continent: 'europe' },
  { isoCode: 'dk', name: 'Denmark', tier: 2, continent: 'europe' },
  { isoCode: 'fi', name: 'Finland', tier: 2, continent: 'europe' },
  { isoCode: 'hr', name: 'Croatia', tier: 2, continent: 'europe' },
  { isoCode: 'ua', name: 'Ukraine', tier: 2, continent: 'europe' },
  { isoCode: 'cz', name: 'Czech Republic', tier: 2, continent: 'europe' },
  { isoCode: 'hu', name: 'Hungary', tier: 2, continent: 'europe' },
  { isoCode: 'rs', name: 'Serbia', tier: 2, continent: 'europe' },
  { isoCode: 'bg', name: 'Bulgaria', tier: 2, continent: 'europe' },
  { isoCode: 'ba', name: 'Bosnia and Herzegovina', tier: 2, continent: 'europe' },
  { isoCode: 'ge', name: 'Georgia', tier: 2, continent: 'asia' },
  { isoCode: 'cy', name: 'Cyprus', tier: 2, continent: 'europe' },
  { isoCode: 'lb', name: 'Lebanon', tier: 2, continent: 'asia' },
  { isoCode: 'ir', name: 'Iran', tier: 2, continent: 'asia' },
  { isoCode: 'pk', name: 'Pakistan', tier: 2, continent: 'asia' },
  { isoCode: 'bd', name: 'Bangladesh', tier: 2, continent: 'asia' },
  { isoCode: 'lk', name: 'Sri Lanka', tier: 2, continent: 'asia' },
  { isoCode: 'th', name: 'Thailand', tier: 2, continent: 'asia' },
  { isoCode: 'vn', name: 'Vietnam', tier: 2, continent: 'asia' },
  { isoCode: 'ph', name: 'Philippines', tier: 2, continent: 'asia' },
  { isoCode: 'my', name: 'Malaysia', tier: 2, continent: 'asia' },
  { isoCode: 'sg', name: 'Singapore', tier: 2, continent: 'asia' },
  { isoCode: 'ng', name: 'Nigeria', tier: 2, continent: 'africa' },
  { isoCode: 'ke', name: 'Kenya', tier: 2, continent: 'africa' },
  { isoCode: 'gh', name: 'Ghana', tier: 2, continent: 'africa' },
  { isoCode: 'et', name: 'Ethiopia', tier: 2, continent: 'africa' },
  { isoCode: 'ma', name: 'Morocco', tier: 2, continent: 'africa' },
  { isoCode: 'dz', name: 'Algeria', tier: 2, continent: 'africa' },
  { isoCode: 'tn', name: 'Tunisia', tier: 2, continent: 'africa' },
  { isoCode: 'ug', name: 'Uganda', tier: 2, continent: 'africa' },
  { isoCode: 'tz', name: 'Tanzania', tier: 2, continent: 'africa' },
  { isoCode: 'zm', name: 'Zambia', tier: 2, continent: 'africa' },
  { isoCode: 'zw', name: 'Zimbabwe', tier: 2, continent: 'africa' },
  { isoCode: 'pa', name: 'Panama', tier: 2, continent: 'americas' },
  { isoCode: 'cr', name: 'Costa Rica', tier: 2, continent: 'americas' },
  { isoCode: 'do', name: 'Dominican Republic', tier: 2, continent: 'americas' },
  { isoCode: 'pe', name: 'Peru', tier: 2, continent: 'americas' },
  { isoCode: 'uy', name: 'Uruguay', tier: 2, continent: 'americas' },
  { isoCode: 'py', name: 'Paraguay', tier: 2, continent: 'americas' },
  { isoCode: 'bo', name: 'Bolivia', tier: 2, continent: 'americas' },

  { isoCode: 'af', name: 'Afghanistan', tier: 3, continent: 'asia' },
  { isoCode: 'al', name: 'Albania', tier: 3, continent: 'europe' },
  { isoCode: 'ad', name: 'Andorra', tier: 3, continent: 'europe' },
  { isoCode: 'ao', name: 'Angola', tier: 3, continent: 'africa' },
  { isoCode: 'ag', name: 'Antigua and Barbuda', tier: 3, continent: 'americas' },
  { isoCode: 'am', name: 'Armenia', tier: 3, continent: 'asia' },
  { isoCode: 'az', name: 'Azerbaijan', tier: 3, continent: 'asia' },
  { isoCode: 'bs', name: 'Bahamas', tier: 3, continent: 'americas' },
  { isoCode: 'bb', name: 'Barbados', tier: 3, continent: 'americas' },
  { isoCode: 'by', name: 'Belarus', tier: 3, continent: 'europe' },
  { isoCode: 'bz', name: 'Belize', tier: 3, continent: 'americas' },
  { isoCode: 'bj', name: 'Benin', tier: 3, continent: 'africa' },
  { isoCode: 'bt', name: 'Bhutan', tier: 3, continent: 'asia' },
  { isoCode: 'bw', name: 'Botswana', tier: 3, continent: 'africa' },
  { isoCode: 'bn', name: 'Brunei', tier: 3, continent: 'asia' },
  { isoCode: 'bf', name: 'Burkina Faso', tier: 3, continent: 'africa' },
  { isoCode: 'bi', name: 'Burundi', tier: 3, continent: 'africa' },
  { isoCode: 'cv', name: 'Cabo Verde', tier: 3, continent: 'africa' },
  { isoCode: 'kh', name: 'Cambodia', tier: 3, continent: 'asia' },
  { isoCode: 'cf', name: 'Central African Republic', tier: 3, continent: 'africa' },
  { isoCode: 'km', name: 'Comoros', tier: 3, continent: 'africa' },
  { isoCode: 'cg', name: 'Congo', tier: 3, continent: 'africa' },
  { isoCode: 'cd', name: 'DR Congo', tier: 3, continent: 'africa' },
  { isoCode: 'dj', name: 'Djibouti', tier: 3, continent: 'africa' },
  { isoCode: 'dm', name: 'Dominica', tier: 3, continent: 'americas' },
  { isoCode: 'sv', name: 'El Salvador', tier: 3, continent: 'americas' },
  { isoCode: 'gq', name: 'Equatorial Guinea', tier: 3, continent: 'africa' },
  { isoCode: 'er', name: 'Eritrea', tier: 3, continent: 'africa' },
  { isoCode: 'ee', name: 'Estonia', tier: 3, continent: 'europe' },
  { isoCode: 'sz', name: 'Eswatini', tier: 3, continent: 'africa' },
  { isoCode: 'fj', name: 'Fiji', tier: 3, continent: 'oceania' },
  { isoCode: 'ga', name: 'Gabon', tier: 3, continent: 'africa' },
  { isoCode: 'gm', name: 'Gambia', tier: 3, continent: 'africa' },
  { isoCode: 'gd', name: 'Grenada', tier: 3, continent: 'americas' },
  { isoCode: 'gt', name: 'Guatemala', tier: 3, continent: 'americas' },
  { isoCode: 'gw', name: 'Guinea-Bissau', tier: 3, continent: 'africa' },
  { isoCode: 'gy', name: 'Guyana', tier: 3, continent: 'americas' },
  { isoCode: 'ht', name: 'Haiti', tier: 3, continent: 'americas' },
  { isoCode: 'hn', name: 'Honduras', tier: 3, continent: 'americas' },
  { isoCode: 'kz', name: 'Kazakhstan', tier: 3, continent: 'asia' },
  { isoCode: 'ki', name: 'Kiribati', tier: 3, continent: 'oceania' },
  { isoCode: 'kp', name: 'North Korea', tier: 3, continent: 'asia' },
  { isoCode: 'kg', name: 'Kyrgyzstan', tier: 3, continent: 'asia' },
  { isoCode: 'la', name: 'Laos', tier: 3, continent: 'asia' },
  { isoCode: 'lv', name: 'Latvia', tier: 3, continent: 'europe' },
  { isoCode: 'ls', name: 'Lesotho', tier: 3, continent: 'africa' },
  { isoCode: 'lr', name: 'Liberia', tier: 3, continent: 'africa' },
  { isoCode: 'ly', name: 'Libya', tier: 3, continent: 'africa' },
  { isoCode: 'li', name: 'Liechtenstein', tier: 3, continent: 'europe' },
  { isoCode: 'lt', name: 'Lithuania', tier: 3, continent: 'europe' },
  { isoCode: 'mg', name: 'Madagascar', tier: 3, continent: 'africa' },
  { isoCode: 'mw', name: 'Malawi', tier: 3, continent: 'africa' },
  { isoCode: 'mv', name: 'Maldives', tier: 3, continent: 'asia' },
  { isoCode: 'mt', name: 'Malta', tier: 3, continent: 'europe' },
  { isoCode: 'mh', name: 'Marshall Islands', tier: 3, continent: 'oceania' },
  { isoCode: 'mr', name: 'Mauritania', tier: 3, continent: 'africa' },
  { isoCode: 'mu', name: 'Mauritius', tier: 3, continent: 'africa' },
  { isoCode: 'fm', name: 'Micronesia', tier: 3, continent: 'oceania' },
  { isoCode: 'md', name: 'Moldova', tier: 3, continent: 'europe' },
  { isoCode: 'mn', name: 'Mongolia', tier: 3, continent: 'asia' },
  { isoCode: 'me', name: 'Montenegro', tier: 3, continent: 'europe' },
  { isoCode: 'mz', name: 'Mozambique', tier: 3, continent: 'africa' },
  { isoCode: 'mm', name: 'Myanmar', tier: 3, continent: 'asia' },
  { isoCode: 'na', name: 'Namibia', tier: 3, continent: 'africa' },
  { isoCode: 'nr', name: 'Nauru', tier: 3, continent: 'oceania' },
  { isoCode: 'np', name: 'Nepal', tier: 3, continent: 'asia' },
  { isoCode: 'ni', name: 'Nicaragua', tier: 3, continent: 'americas' },
  { isoCode: 'ne', name: 'Niger', tier: 3, continent: 'africa' },
  { isoCode: 'mk', name: 'North Macedonia', tier: 3, continent: 'europe' },
  { isoCode: 'om', name: 'Oman', tier: 3, continent: 'asia' },
  { isoCode: 'pw', name: 'Palau', tier: 3, continent: 'oceania' },
  { isoCode: 'pg', name: 'Papua New Guinea', tier: 3, continent: 'oceania' },
  { isoCode: 'rw', name: 'Rwanda', tier: 3, continent: 'africa' },
  { isoCode: 'kn', name: 'Saint Kitts and Nevis', tier: 3, continent: 'americas' },
  { isoCode: 'lc', name: 'Saint Lucia', tier: 3, continent: 'americas' },
  { isoCode: 'vc', name: 'Saint Vincent and the Grenadines', tier: 3, continent: 'americas' },
  { isoCode: 'ws', name: 'Samoa', tier: 3, continent: 'oceania' },
  { isoCode: 'sm', name: 'San Marino', tier: 3, continent: 'europe' },
  { isoCode: 'st', name: 'Sao Tome and Principe', tier: 3, continent: 'africa' },
  { isoCode: 'sc', name: 'Seychelles', tier: 3, continent: 'africa' },
  { isoCode: 'sl', name: 'Sierra Leone', tier: 3, continent: 'africa' },
  { isoCode: 'sb', name: 'Solomon Islands', tier: 3, continent: 'oceania' },
  { isoCode: 'so', name: 'Somalia', tier: 3, continent: 'africa' },
  { isoCode: 'ss', name: 'South Sudan', tier: 3, continent: 'africa' },
  { isoCode: 'tj', name: 'Tajikistan', tier: 3, continent: 'asia' },
  { isoCode: 'tl', name: 'Timor-Leste', tier: 3, continent: 'asia' },
  { isoCode: 'tg', name: 'Togo', tier: 3, continent: 'africa' },
  { isoCode: 'to', name: 'Tonga', tier: 3, continent: 'oceania' },
  { isoCode: 'tt', name: 'Trinidad and Tobago', tier: 3, continent: 'americas' },
  { isoCode: 'tm', name: 'Turkmenistan', tier: 3, continent: 'asia' },
  { isoCode: 'tv', name: 'Tuvalu', tier: 3, continent: 'oceania' },
  { isoCode: 'uz', name: 'Uzbekistan', tier: 3, continent: 'asia' },
  { isoCode: 'vu', name: 'Vanuatu', tier: 3, continent: 'oceania' },
  { isoCode: 'va', name: 'Vatican City', tier: 3, continent: 'europe' },

  { isoCode: 'td', name: 'Chad', tier: 4, continent: 'africa' },
  { isoCode: 'ro', name: 'Romania', tier: 4, continent: 'europe' },
  { isoCode: 'mc', name: 'Monaco', tier: 4, continent: 'europe' },
  { isoCode: 'id', name: 'Indonesia', tier: 4, continent: 'asia' },
  { isoCode: 'ie', name: 'Ireland', tier: 4, continent: 'europe' },
  { isoCode: 'ci', name: 'Côte d’Ivoire', tier: 4, continent: 'africa' },
  { isoCode: 'ml', name: 'Mali', tier: 4, continent: 'africa' },
  { isoCode: 'gn', name: 'Guinea', tier: 4, continent: 'africa' },
  { isoCode: 'nl', name: 'Netherlands', tier: 4, continent: 'europe' },
  { isoCode: 'lu', name: 'Luxembourg', tier: 4, continent: 'europe' },
  { isoCode: 'is', name: 'Iceland', tier: 4, continent: 'europe' },
  { isoCode: 'nz', name: 'New Zealand', tier: 4, continent: 'oceania' },
  { isoCode: 'au', name: 'Australia', tier: 4, continent: 'oceania' },
  { isoCode: 'si', name: 'Slovenia', tier: 4, continent: 'europe' },
  { isoCode: 'sk', name: 'Slovakia', tier: 4, continent: 'europe' },
  { isoCode: 'ye', name: 'Yemen', tier: 4, continent: 'asia' },
  { isoCode: 'sy', name: 'Syria', tier: 4, continent: 'asia' },
  { isoCode: 'iq', name: 'Iraq', tier: 4, continent: 'asia' },
  { isoCode: 'jo', name: 'Jordan', tier: 4, continent: 'asia' },
  { isoCode: 'co', name: 'Colombia', tier: 4, continent: 'americas' },
  { isoCode: 'ec', name: 'Ecuador', tier: 4, continent: 'americas' },
  { isoCode: 've', name: 'Venezuela', tier: 4, continent: 'americas' },
  { isoCode: 'sn', name: 'Senegal', tier: 4, continent: 'africa' },
  { isoCode: 'cm', name: 'Cameroon', tier: 4, continent: 'africa' },
  { isoCode: 'bh', name: 'Bahrain', tier: 4, continent: 'asia' },
  { isoCode: 'qa', name: 'Qatar', tier: 4, continent: 'asia' },
  { isoCode: 'pl', name: 'Poland', tier: 4, continent: 'europe' },
  { isoCode: 'at', name: 'Austria', tier: 4, continent: 'europe' },
  { isoCode: 'cl', name: 'Chile', tier: 4, continent: 'americas' },
  { isoCode: 'kw', name: 'Kuwait', tier: 4, continent: 'asia' },
  { isoCode: 'sd', name: 'Sudan', tier: 4, continent: 'africa' },
  { isoCode: 'sr', name: 'Suriname', tier: 3, continent: 'americas' },
  { isoCode: 'ae', name: 'United Arab Emirates', tier: 4, continent: 'asia' },
];

export function getCountriesByContinent(continent?: Continent): CountryFlag[] {
  if (!continent || continent === 'world') {
    return COUNTRIES;
  }
  return COUNTRIES.filter((c) => c.continent === continent);
}
